### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by codepathreview** [SarthakM9/TodoApp#1]
Hi Sarthak,

Looks great, this exercise is intended in part to give you an introduction to the general rhythm of the observer track. The observer track is entirely project-based with an app being given each week to build. Each project builds on the last to help each engineer learn the practical elements of Android development and best practices as quickly as possible. 

Great to see you were able to complete a large number of extensions to your app already. Your project looks very well-done. As you can probably tell, the extension tasks available on each project are the valuable learnings since they dive deeper into common real-world Android use cases.

Be sure to take a look through our [organizing your source files guide](http://guides.codepath.com/android/Organizing-your-Source-Files#android-folder-structure) for tips on organizing your code as well.

We'll be following up with you again shortly to outline the next steps of becoming a self-paced observer.

**Comment by SarthakM9** [comment]
Thank you! :)
